name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Log out from DockerHub
        run: docker logout

  slackNotification:
  needs: docker
  name: Slack Notification
  runs-on: ubuntu-latest
  steps:
    - name: Send Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_CHANNEL }}
      with:
        message: "The project ${{ github.repository }} has been successfully built and pushed to DockerHub."
        username: "CI Pipeline Bot"
        icon_emoji: ":rocket:" 

  discordNotification:
    needs: docker
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_URL }}
        with:
          args: 'The project ${{ github.repository }} has been successfully built and pushed to DockerHub.'
